name: test-nodejs

on:
  push:
    branches: [ encoder]
  pull_request:
    branches: [ encoder ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run format
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
